# Dockerfile

# FROM directive instructing base image to build upon
FROM python:2-onbuild

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN python manage.py migrate
COPY . .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
